### PR TITLE
MSGraphForSharePoint: Feature - copy item, create folder, list drive children actions

### PR DESCRIPTION
**Pull request by asur1on**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [X] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

No security considerations applicable, no changes in authentication methods, no file system changes, etc.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

Added 3 new actions supported by Graph API: copy item, create folder, and list drive children

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

copy item to take an existing file and make a duplicate or move it to another location
create folder to create new folder in SharePoint
list drive children to list children items for a specific Drive ID

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

NA

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

NA

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by achandya-crest** [comment]
Hello @asur1on,
I see that there are conflicts due to a new release of the app with version 1 3.0 in splunk-soar-connector:next branch. Could you please resolve them so that your changes are added on the latest build?

**Comment by achandya-crest** [comment]
I have pulled the latest changes and will start working on this PR.

**Comment by achandya-crest** [comment]
Hello @asur1on, I checked the copy item action and have a few queries. 

1. I see the code has the below lines:
**else:
            data = {
                "parentReference": {"driveId": dest_folder_id, "id": dest_folder_id}
            }**

 I believe it should be this:
**else:
            data = {
                "parentReference": {"driveId": dest_drive_id, "id": dest_folder_id}
            }**


Could you please check?


2. Also without providing file_name parameter, is it possible to successfully copy the item using copy item action?

3. Also for all the 3 features added, I will be adding an APP_SUCCESS message. Would it be fine for you? Or you can also add it.

**Comment by achandya-crest** [comment]
Hello @asur1on, Did you get a chance to look into this https://github.com/splunk-soar-connectors/msgraphforsharepoint/pull/13#issuecomment-1779187385?

**Comment by achandya-crest** [comment]
> @achandya-crest Sorry for the delay.
> 
> 1. Yes, that fix should be fine, not sure what I was thinking there
> 2. Am I missing an APP_SUCCESS somewhere? I see one example at https://github.com/asur1on/msgraphforsharepoint/blob/copy_create/msgraphforsharepoint_connector.py#L811
> 3. I think dest_folder_id being optional should be fine, I wasn't sure based on Microsoft's documentation if dest_drive and dest_folder are both required.
> 4. How do you think copy_item should look with an optional file_name and optional dest_folder_id?

1. I have made the code change
2. I'll make the message changes
3. I guess even if it works without dest_folder_id but if the doc says **This example copies a file identified by {item-id} into a folder identified with a driveId and id value.** then let's keep it that way according to documentation.

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
